name: CI

on:
  push:
    branches:
      - main
      - experimental

  pull_request:
    branches:
      - main
      - experimental

jobs:
  setup_env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'maven'

      - name: Check code formatting
        run: mvn formatter:validate
        continue-on-error: false

#  validate_formatting:
#    runs-on: ubuntu-latest
#    needs: [ setup_env ]
#
#    steps:
#      - name: Check code formatting
#        run: mvn formatter:validate
#        continue-on-error: false
#
#  compile:
#    runs-on: ubuntu-latest
#    needs: [ validate_formatting ]
#
#    steps:
#      - name: Compile code base
#        run: mvn compile
#        continue-on-error: false
#
#  run_tests:
#    runs-on: ubuntu-latest
#    needs: [ compile ]
#
#    steps:
#      - name: Run tests
#        run: mvn test
#        continue-on-error: false

  notify_on_failure_if_pr:
    runs-on: ubuntu-latest
    needs: [ validate_formatting, compile, run_tests, setup_env]

    if: failure()

    steps:
      - name: Send notification
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const { number, pull_request } = context.issue;

            if(pull_request) {
            
              let message = '';
  
              message = ':x:A Workflow Job failed, please click on **Show all checks** for more details\n';
              message += '\nRemember: always format, compile and test your code before attempting a push.\nThanks!'
  
  
              const body = {
                owner,
                repo,
                issue_number: number,
                body: message
              };
  
              await github.rest.issues.createComment(body);
            }
            
            
            
            
            

