name: Development CI

on:
  push:
    branches:
      - "tp*"
  pull_request:
    branches:
      - main
      - experimental

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'maven'

      - name: Check code formatting
        run: mvn formatter:validate
        continue-on-error: false

      - name: Compile and fail on errors
        run: mvn compile
        continue-on-error: false

      - name: Run tests
        run: mvn test
        continue-on-error: false
