name: CI

on:
  push:
    branches:
      - main
      - experimental
  pull_request:
    branches:
      - main
      - experimental

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

  validate_formatting:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check code formatting
        run: mvn formatter:validate
        continue-on-error: false

  compile:
    runs-on: ubuntu-latest
    needs: [ validate_formatting ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile and fail on errors
        run: mvn compile
        continue-on-error: false

  run_tests:
    runs-on: ubuntu-latest
    needs: [ validate_formatting ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: mvn test
        continue-on-error: false


  notify_on_failure:
    runs-on: ubuntu-latest
    needs: [ build ]

    if: failure()

    steps:
      - name: Send notification
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const { number, pull_request } = context.issue;

            if(pull_request) {

              let message = '';

              message = ':x:A Workflow Job failed, please click on **Show all checks** for more details\n';
              message += '\nRemember: always format, compile and test your code before attempting a push.\nThanks!'


              const body = {
                owner,
                repo,
                issue_number: number,
                body: message
              };

              await github.rest.issues.createComment(body);
            }
    
    
            
            
            

