name: Development CI

on:
  push:
    branches:
      - "tp*"
  pull_request:
    branches:
      - main
      - experimental

jobs:
  setup_env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'maven'

  validate_formatting:
    runs-on: ubuntu-latest
    needs: [ setup_env ]

    steps:
      - name: Check code formatting
        run: mvn formatter:validate
        continue-on-error: false

  compile:
    runs-on: ubuntu-latest
    needs: [ validate_formatting ]

    steps:
      - name: Compile code base
        run: mvn compile
        continue-on-error: false

  run_tests:
    runs-on: ubuntu-latest
    needs: [ compile ]

    steps:
      - name: Run tests
        run: mvn test
        continue-on-error: false

  notify:
    runs-on: ubuntu-latest
    needs: [ validate_formatting, compile, run_tests ]

    if: github.event_name == 'pull_request'

    steps:
      - name: Send notification
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;
            
            let message = '';
            const failedJobs = context.payload.workflow_run.jobs.filter(job => job.conclusion === 'failure');   
            
            if (failedJobs.length > 0) {
              message = 'The following job failed:\n';
              message += `\t- ${failedJobs[0]}\n`;
              message += '\nRemember: always format, compile and test your code before pushing.\nThanks!'
            
            
              const body = {
                owner,
                repo,
                issue_number: number,
                body: message
              };
              
              await github.rest.issues.createComment(body);
            } 
            
            

